version = 1

[[configs]]
id = "hyprland"
path = "modules/configs/hyprland"
enabled_by_default = true

[[configs]]
id = "niri"
path = "modules/configs/niri"
enabled_by_default = false

[[configs]]
id = "gnome"
path = "modules/configs/gnome"
enabled_by_default = true

[[configs]]
id = "cosmic"
path = "modules/configs/cosmic"
enabled_by_default = true
