# Iron Rust Formatting Configuration
# https://rust-lang.github.io/rustfmt/

edition = "2024"
max_width = 100
tab_spaces = 4
use_small_heuristics = "Default"

# Imports
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true

# Comments
wrap_comments = true
comment_width = 80
normalize_comments = true

# Other
format_code_in_doc_comments = true
format_strings = true
use_field_init_shorthand = true
use_try_shorthand = true
