# Input defaults

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    mouse_refocus = true
    accel_profile = flat

    touchpad {
        natural_scroll = true
        tap-to-click = true
        drag_lock = false
        disable_while_typing = true
    }

    sensitivity = 0.0
}

gestures {
    workspace_swipe = true
    workspace_swipe_invert = false
    workspace_swipe_distance = 300
}
