# Window rules

# Keep dialogs floating by default
windowrulev2 = float, class:^(pavucontrol|blueman-manager|nm-connection-editor)$
windowrulev2 = center, class:^(pavucontrol|blueman-manager|nm-connection-editor)$

# Common utility windows
windowrulev2 = float, title:^(Picture in picture)$
windowrulev2 = pin, title:^(Picture in picture)$

# Improve compatibility for some XWayland apps
windowrulev2 = suppressevent maximize, class:.*
