# Main entrypoint. Keep this file minimal and include modular files.
source = ./00-env.conf
source = ./10-input.conf
source = ./20-monitors.conf
source = ./30-workspaces.conf
source = ./40-keybinds.conf
source = ./50-window-rules.conf
source = ./90-autostart.conf

source = ./host-overrides.conf
