profile = "main"
id = "archlinux"
name = "archlinux's Iron Host"
installed_bundles = []

[hardware]
cpu = "AMD Ryzen 7 9800X3D 8-Core Processor"
gpu = "Advanced Micro Devices, Inc. [AMD/ATI] Navi 44 [Radeon RX 9060 XT] (rev c0)"
ram_mb = 31189
chassis = "Desktop"

[[hardware.monitors]]
output = "DP-1"
resolution = "1920x1080"
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "DP-2"
resolution = "2560x1440"
refresh_rate = 60
scale = 1.0
