profile = "main"
id = "archlinux"
name = "archlinux's Iron Host"
installed_bundles = []

[hardware]
cpu = "AMD Ryzen 7 9800X3D 8-Core Processor"
gpu = "Advanced Micro Devices, Inc. [AMD/ATI] Navi 44 [Radeon RX 9060 XT] (rev c0)"
ram_mb = 31189
chassis = "Desktop"

[[hardware.monitors]]
output = "DP-1"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "Make:"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "Model:"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "Serial:"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "Physical"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "Enabled:"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "Modes:"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1920x1080"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1600x900"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1280x1024"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1280x1024"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1152x864"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1024x768"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1024x768"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "800x600"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "800x600"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "640x480"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "640x480"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "720x400"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "Position:"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "Transform:"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "Scale:"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "Adaptive"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "DP-2"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "Make:"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "Model:"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "Serial:"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "Physical"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "Enabled:"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "Modes:"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "2560x1440"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "2560x1440"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "2560x1440"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "2560x1440"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1920x1080"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1920x1080"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1920x1080"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1920x1080"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1680x1050"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1280x1024"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1280x1024"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1440x900"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1280x960"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1152x864"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1280x720"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1280x720"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1280x720"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1280x720"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1440x576"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1440x576"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1024x768"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1024x768"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1024x768"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1440x480"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1440x480"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1440x480"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "1440x480"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "800x600"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "800x600"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "800x600"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "800x600"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "720x576"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "720x576"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "720x480"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "720x480"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "720x480"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "720x480"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "640x480"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "640x480"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "640x480"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "640x480"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "640x480"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "640x480"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "720x400"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "Position:"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "Transform:"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "Scale:"
resolution = ""
refresh_rate = 60
scale = 1.0

[[hardware.monitors]]
output = "Adaptive"
resolution = ""
refresh_rate = 60
scale = 1.0
