[FileDialog]
history=file:///home/don/Pictures/Screenshots, file:///home/don/BlackDon/Edited Videos, file:///home/don/BlackDon/Thumbnails, file:///home/don/BlackDon, file:///home/don/Downloads
lastVisited=file:///home/don/BlackDon/Edited Videos
qtVersion=6.10.2
shortcuts=file:, file:///home/don
sidebarWidth=118
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2\x8f\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1T\0\0\0\x1\0\0\0\0\0\0\0T\0\0\0\x1\0\0\0\0\0\0\0U\0\0\0\x1\0\0\0\0\0\0\0\x92\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)
viewMode=Detail
